Create CODE_OF_CONDUCT
tidev/organization-docs pull request #12
Opened 2022-01-04 23:38 UTC by joshualambert

2022-01-04 23:40 UTC, joshualambert commented
@cb1kenobi Take a look at this please. Proposed community code-of-conduct based on MariaDB's code of conduct. Wording has been cleaned up and formatted in markdown for optimal display here on Github.

2022-01-05 04:19 UTC, cb1kenobi requested changes

2022-01-05 04:19 UTC, cb1kenobi commented on CODE_OF_CONDUCT.md
> +Feedback is always appreciated! If you have any feedback or suggestions on how to improve the MariaDB Community Code of Conduct, please file an issue on the TiDev Organizational Docs repository here:
s/MariaDB/TiDev/ :)

2022-01-05 15:04 UTC, cb1kenobi approved these changes
Looks great! Thanks!

2022-01-05 15:04 UTC, merged